# Single-node Teleport cluster called "one" (runs all 3 roles: proxy, auth and node)
teleport:
  nodename: one
  log:
    output: /var/lib/teleport/teleport.log
    severity: INFO

auth_service:
  enabled: yes
  cluster_name: one
  tokens: 
       - "node,auth,proxy:xxx"

  # to enable trusted clusters, execute `tctl auth export > data/two/two.ca` inside container "two-auth"
  # and then uncomment this and restart container "one"
  trusted_clusters:
      - key_file: /root/go/src/github.com/gravitational/teleport/docker/data/two/two.ca

ssh_service:
  enabled: yes
  labels:
      cluster: one
  commands:
      - name: kernel
        command: [/bin/uname, -r]
        period: 5m

proxy_service:
  enabled: yes
